### ISSUE TITLE
按照README操作启动时报错，错误信息如下

### ISSUE THREAD

**Issue by firmboy** [davidfantasy/mybatis-plus-generator-ui#1]
pom依赖：
`

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>2.1.2</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.ojdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.github.davidfantasy</groupId>
            <artifactId>mybatis-plus-generator-ui</artifactId>
            <version>1.0.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>`
代码结构：
![image](https://user-images.githubusercontent.com/21125632/83212483-51ecec00-a192-11ea-926f-e5022bac2cc0.png)
报错信息：
![image](https://user-images.githubusercontent.com/21125632/83212535-734dd800-a192-11ea-820d-3449ca99cf91.png)

**Comment by davidfantasy** [comment]
这个应该不是generator server抛出的错误，可能和你环境springboot热部署有关系。可以参考https://blog.csdn.net/my13413527259/article/details/80268609 的解决方式
