### ISSUE TITLE
SQL代码生成：只能通过查询语句生成DTO对象，请检查SQL

### ISSUE THREAD

**Issue by vjsplus** [davidfantasy/mybatis-plus-generator-ui#108]
### 当前使用版本(必填,否则不予处理)
<dependency>
    <groupId>com.github.davidfantasy</groupId>
    <artifactId>mybatis-plus-generator-ui</artifactId>
    <version>2.0.1</version>
</dependency>

### 重现步骤(如果有就写完整)
你好，我第一次使用通过SQL生成代码的功能。我的sql语句使用Navicat验证是正确的，但是页面报"只能通过查询语句生成DTO对象，请检查SQL"。
我有疑问是否支持SQL迭代查询呢？
![WX20231207-153342](https://github.com/davidfantasy/mybatis-plus-generator-ui/assets/152485478/0b7d04ee-1e77-4e97-bb83-86da4c7b96a8)

`sql
WITH RECURSIVE company_hierarchy 
AS (SELECT id, company_name, super_id 
    FROM gmd_company_info
    WHERE id = '#{companyId}'
    UNION ALL
    SELECT c.id, c.company_name, c.super_id
    FROM gmd_company_info c
    INNER JOIN company_hierarchy ch ON c.super_id = ch.id)
SELECT * FROM company_hierarchy
`

### 报错信息
只能通过查询语句生成DTO对象，请检查SQL

**Comment by davidfantasy** [comment]
SQL 生成DTO目前对查询语句做了语法解析，你这个语法太复杂了，应该是SQL解析框架无法将其识别为一个查询语句
