### ISSUE TITLE
自定义配置生成代码异常

### ISSUE THREAD

**Issue by xyhuangjia** [davidfantasy/mybatis-plus-generator-ui#12]
### 当前使用版本(必填,否则不予处理)
1.1.0
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
自定义配置生成代码异常
### 重现步骤(如果有就写完整)
代码生成-> 输出配置->新增(如下图)
<img width="1350" alt="截屏2020-06-18 下午5 07 50" src="https://user-images.githubusercontent.com/12025585/85001436-4041a780-b186-11ea-85ea-b70ce28318be.png">
-> 代码生成->
<img width="965" alt="截屏2020-06-18 下午5 08 53" src="https://user-images.githubusercontent.com/12025585/85001615-741ccd00-b186-11ea-8317-aa0218bcd47f.png">
### 报错信息

建议：生成文件和删除文件使用文件索引操作
鶸希望能修改这一部分，然后提一个pr

**Comment by davidfantasy** [comment]
从图上看不出来报的是什么错，看起来是因为类文件名称和类名不一致导致的，你在自定义输出文件的时候，模板是使用的entity的模板，如果没有在模板中修改类名的生成规则，DTO名称还是会延用的Entity的名称规则，导致和你定义的DTO文件的命名规则不一致。

**Comment by xyhuangjia** [comment]
> 从图上看不出来报的是什么错，看起来是因为类文件名称和类名不一致导致的，你在自定义输出文件的时候，模板是使用的entity的模板，如果没有在模板中修改类名的生成规则，DTO名称还是会延用的Entity的名称规则，导致和你定义的DTO文件的命名规则不一致。

很多同学是没时间和精力或者能力去自定义模版的，我个人觉得我们可以提供一套基于五个基础模版快速生成代码的方式

**Comment by davidfantasy** [comment]
mybatis-plus-generator框架内置的支持也只有Entity,Mapper,Mapper.xml,Service,Controller这五种，单独为数据表生成一个DTO对象不是普遍的需求，1.1.0版本加上了可以根据SQL查询结果自动生成DTO对象的功能我觉得基本就够了。后续如果有更多人提出再考虑增加内置模板。

**Comment by xyhuangjia** [comment]
> mybatis-plus-generator框架内置的支持也只有Entity,Mapper,Mapper.xml,Service,Controller这五种，单独为数据表生成一个DTO对象不是普遍的需求，1.1.0版本加上了可以根据SQL查询结果自动生成DTO对象的功能我觉得基本就够了。后续如果有更多人提出再考虑增加内置模板。

OK,目前我们公司中台要求内部数据要求全是以DTO结尾，里面实质是还是Entity的内容。
