### ISSUE TITLE
问题总结，对应处理

### ISSUE THREAD

**Issue by Descarify** [davidfantasy/mybatis-plus-generator-ui#121]
1问题-配置文件保存在哪里，移动项目后丢失。解决方案： 配置文件默认保存在系统用户盘，在userconfigstor.java中调整存储位置到项目中，配置文件名称为user-config.json
public void afterPropertiesSet()throws Exception {
// this.storeDir = Pathutil.joinPath(System.getProperty("user.home”), CONFIG HOME, generatorConfig.getBasePackage());//this.userConfigPath = this.storeDir + File.separator + "user-config.json";
this.storeDir = PathUtil.joinPath(System.getProperty("user.dir"));this.userConfigPath = this.storeDir + File.separator + "user-config.json",
2 模板怎么使用？解决方案：不同项目不同模板，建议把使用的模板放到最外，直接使用，不适用的建立文件夹放进去备用，原始的留着
3 配置怎么保存？解决方案：启动项目，浏览器访问后，进行相关配置，并保存配置，保存后会保存到user-config.json文件中
4 如何修改sql生成类的名称和模块位置？解决方案：DtostrategyForm.vue中的handleMapperMethodInput方法中修改sql语句生成的条件和返回实体名称和模块
5 分页通用处理：mapper中的方法分页时，Sq1Generatorservice类中以下方法改为返回1ist，通用查询，可支持分页也可不用分页String lastReturnType = returnType.replaceFirst("List","Page");JavaClassMethodInfo methodInfo = JavaclassMethodInfo.builder()
.classRef(daoClassRef).methodName(config.getMapperMethod())//.returnType(returnType).returnType(lastReturnType)importJavaTypes(imports).params(methodParams).build();
javaClassParser.addMethod2Interface(methodInfo);
6 bug修复：AutoCompleteServiceAutoCompleteservice类中，
//此处有bug，参数顺序不对
// doSearch(new File(mapperRootPath),DOT XML, searchKey,hitNames),doSearch(new File(mapperRootPath),searchKey, DoT XML, hitNames);
7 使用技巧总结:先找到一个表，生成空，什么都不选，刷新项目根路径，即选中要生成到的项目的绝对路径，之后再生成sq1语句

**Comment by testfengjing** [comment]
你发的邮件已经收到！
Thanks with Best regards,
