### ISSUE TITLE
查询库表的sql有问题

### ISSUE THREAD

**Issue by jackxu2011** [davidfantasy/mybatis-plus-generator-ui#13]
### 当前使用版本(必填,否则不予处理)
1.1.0
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
oracle, db2, postgreSql等无法查到表，与mybatis-generator中的sql语句有关
### 重现步骤(如果有就写完整)
![image](https://user-images.githubusercontent.com/4495830/85265384-c0c51880-b4a4-11ea-93f4-4b7c553c9e66.png)

![image](https://user-images.githubusercontent.com/4495830/85265452-dfc3aa80-b4a4-11ea-98dd-05717ad60485.png)
mybatis-generator 是一个模块字段串，不是真实的sql
### 报错信息
无报错信息，页面无法看到表。

**Comment by davidfantasy** [comment]
新发布的1.1.1版已修复，新增配置项schemaName用于指定部分数据库类型的schema。我这边没有测试条件验证所有数据库，如果测试还有问题请在此问题下留言。

**Comment by jackxu2011** [comment]
ok， 我也是发现没有查出表，去看了一下代码。谢谢
