### ISSUE TITLE
sql代码生成有问题

### ISSUE THREAD

**Issue by ronghuaxueleng** [davidfantasy/mybatis-plus-generator-ui#14]
### 当前使用版本(必填,否则不予处理)
1.1.0
### 重现步骤(如果有就写完整)
![微信截图_20200623171634](https://user-images.githubusercontent.com/9460517/85386081-b757b100-b575-11ea-8285-a0e4f951c7a6.png)
这段代码判断有问题吧
### 报错信息
不是合法的包名：xxx

**Comment by davidfantasy** [comment]
请贴出你是操作什么功能，输入的什么值引发的这个错误

**Comment by ronghuaxueleng** [comment]
![微信截图_20200624091225](https://user-images.githubusercontent.com/9460517/85485213-d8161a00-b5fa-11ea-9503-69b3b6c68053.png)
就这个操作 Mapper引用为java的时候，那个判断有问题

**Comment by davidfantasy** [comment]
这个地方选择JAVA源码目录时确实有问题，下个版本会修复

**Comment by davidfantasy** [comment]
1.1.2已解决
