### ISSUE TITLE
tableName 应该先toLowerCase()

### ISSUE THREAD

**Issue by jackxu2011** [davidfantasy/mybatis-plus-generator-ui#15]
### 当前使用版本(必填,否则不予处理)
1.1.1
### 该问题是如何引起的？(确定最新版也有问题再提!!!)

![image](https://user-images.githubusercontent.com/4495830/85389471-099ad100-b57a-11ea-8f84-bfcca6b02728.png)

### 重现步骤(如果有就写完整)
如果表名为全大写且没有下划线，则类名变为全大写

**Comment by davidfantasy** [comment]
这个是默认的转换策略，可以优化一下；实际上可以通过在GeneratorConfig中指定NameConverter来自定义满足不同命名规则的转换策略

**Comment by xyhuangjia** [comment]
表名不该是下划线和小写字母么？

**Comment by jackxu2011** [comment]
不同的数据库不一样，有些数据库默认是大写字母

**Comment by davidfantasy** [comment]
1.1.2 已解决
