### ISSUE TITLE
希望配置能更灵活

### ISSUE THREAD

**Issue by CsyDesign** [davidfantasy/mybatis-plus-generator-ui#17]
希望配置能更灵活，希望能在UI上定制mybatis-plus-generator的所有配置；

举个例子：
不同人对包名都有不同的命名习惯，比如我想把mapper命名为dao，把entity命名为po等；
但是目前版本对这种需求操作起来还不是很方便。

加油 大佬

**Comment by davidfantasy** [comment]
你说的这个配置在**首页-table代码生成-输出配置**里面就可以修改，可以自行定义每种类型文件的输出包目录；现在的设计策略是如果只需要设置一次，以后都不太会改的东西，就会放到输出配置中进行设置；如果每次生成的时候可能都有变化的配置，会放到生成时弹出框里面方便修改；如果你有更好的建议可以提出来参考一下。
![微信截图_20200717101430](https://user-images.githubusercontent.com/6639987/87741314-ca793c00-c816-11ea-90c1-89b842eaba9a.png)

**Comment by xyhuangjia** [comment]
@CsyDesign 我能理解大佬，我们部门现现在包名就是com.xx.model，但是里面对象是以DO结尾，坑爹的一笔。所以还是依然建议 @davidfantasy 分离文件名和类型标识

**Comment by davidfantasy** [comment]
类型标识和文件名是分开的啊，如果觉得默认的文件名不合适，可以直接继承NameConverter，实现自己的文件名命名规则；这个东西就是考虑到灵活性，所以是以代码接口的方式实现的，如果每次在页面上填写就太麻烦了，类似像这样(NameConverter的实现方式可以参考**com.github.davidfantasy.mybatisplus.generatorui.mbp.DefaultNameConverter**)：
~~~java
GeneratorConfig config = GeneratorConfig.builder().jdbcUrl("jdbc:mysql://192.168.1.211:3306/test")
                .userName("root")
                .password("root")
                .nameConverter(new NameConverter() {
                    @Override
                    public String entityNameConvert(String tableName) {
                        return null;
                    }

                    @Override
                    public String propertyNameConvert(String fieldName) {
                        return null;
                    }

                    @Override
                    public String outputFileNameConvert(String fileType, String entityName) {
                        return null;
                    }
                })
                .port(8068)
                .driverClassName("com.mysql.cj.jdbc.Driver")
                .basePackage("com.github.davidfantasy.mybatisplus.generatorui.example")
                .build();
~~~

**Comment by CsyDesign** [comment]
也是个办法，就是有点魔改的意思了

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："davidfantasy "<notifications@github.com&gt;;
发送时间：2020年7月22日(星期三) 上午10:22
收件人："davidfantasy/mybatis-plus-generator-ui" <mybatis-plus-generator-ui@noreply.github.com&gt;;
抄送："CsyDesign "<drcsy@csy.design&gt;;"Mention "<mention@noreply.github.com&gt;;
主题：Re: [davidfantasy/mybatis-plus-generator-ui] 希望配置能更灵活 (#17)
-----------------------------------

 

 
类型标识和文件名是分开的啊，如果觉得默认的文件名不合适，可以直接继承NameConverter，实现自己的文件名命名规则；这个东西就是考虑到灵活性，所以是以代码接口的方式实现的，如果每次在页面上填写就太麻烦了，类似像这样(NameConverter的实现方式可以参考com.github.davidfantasy.mybatisplus.generatorui.mbp.DefaultNameConverter)：
 GeneratorConfig config = GeneratorConfig.builder().jdbcUrl("jdbc:mysql://192.168.1.211:3306/test")                 .userName("root")                 .password("root")                 .nameConverter(new NameConverter() {                     @Override                     public String entityNameConvert(String tableName) {                         return null;                     }                     @Override                     public String propertyNameConvert(String fieldName) {                         return null;                     }                     @Override                     public String outputFileNameConvert(String fileType, String entityName) {                         return null;                     }                 })                 .port(8068)                 .driverClassName("com.mysql.cj.jdbc.Driver")                 .basePackage("com.github.davidfantasy.mybatisplus.generatorui.example")                 .build();

**Comment by davidfantasy** [comment]
1.2.0版本已优化对于类名和文件名的自定义方式，现在只需要对NameConverter的对应方法进行覆写，即可定义对应类型文件的类名和文件名
