### ISSUE TITLE
表字段大写的情况,生成的entity也是全大写

### ISSUE THREAD

**Issue by luckylk** [davidfantasy/mybatis-plus-generator-ui#2]

**Comment by davidfantasy** [comment]
默认的实现只是将下划线转驼峰，可以自行实现NameConverter.propertyNameConvert来自定义表字段名称的转换规则，例如：
`
GeneratorConfig config = GeneratorConfig.builder().jdbcUrl("jdbc:mysql://192.168.1.211:3306/cimc-user-center")
                .userName("root")
                .password("root")
                .driverClassName("com.mysql.cj.jdbc.Driver")
                .basePackage("example")
                .nameConverter(new DefaultNameConverter(){
                    @Override
                    public String propertyNameConvert(String fieldName) {
                        return null;
                    }
                 })
                .port(8068)
                .build();
`
