### ISSUE TITLE
命名策略部分生效

### ISSUE THREAD

**Issue by jackxu2011** [davidfantasy/mybatis-plus-generator-ui#20]
### 当前使用版本(必填,否则不予处理)
1.1.2
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
重新定义命令策略
只有文件名生效，内容没有生效主要体现在service, 与serviceImpl
### 报错信息

原因  mybatis-plus-generator有自己的命名策略，在设置 NameConverter 时，没有覆盖mybatis-plus-generator的生成策略

![image](https://user-images.githubusercontent.com/4495830/88145136-90e86c80-cc2c-11ea-926b-6e0970fff6b5.png)

**Comment by davidfantasy** [comment]
1.2.0版本已修复，注意新的自定义命名策略
