### ISSUE TITLE
项目引入后正常启动，但是访问时加载静态资源失败

### ISSUE THREAD

**Issue by zhao6868820** [davidfantasy/mybatis-plus-generator-ui#21]
### 当前使用版本(必填,否则不予处理)
		<dependency>
			<groupId>com.github.davidfantasy</groupId>
			<artifactId>mybatis-plus-generator-ui</artifactId>
			<version>1.2.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.github.davidfantasy</groupId>
			<artifactId>mybatis-plus-generator-ui</artifactId>
			<version>1.1.4</version>
			<scope>test</scope>
		</dependency>
二个版本都试了，浏览器缓存也清理了。
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
目前2个版本都可以正常启动，但是访问时后台无日志显示，前端F12提示：
GET http://localhost:8068/_nuxt/962aa799c3350e0f5754.js net::ERR_ABORTED 404
### 重现步骤(如果有就写完整)
1、启动项目
2、浏览器数据地址访问
3、访问失败，页面一直转圈
### 报错信息
另外我是用的oracle数据库，我想咨询启动方法里面的schemaName（""）属性值是什么？
下面是报错信息：
GET http://localhost:8068/_nuxt/962aa799c3350e0f5754.js net::ERR_ABORTED 404
![image](https://user-images.githubusercontent.com/39057941/88374468-67664700-cdcc-11ea-813e-4cc8afcf20cc.png)
![image](https://user-images.githubusercontent.com/39057941/88374494-71884580-cdcc-11ea-89c0-db8fe88a92e0.png)
![image](https://user-images.githubusercontent.com/39057941/88374602-8e247d80-cdcc-11ea-9e4e-4c59f2b19eb7.png)

**Comment by davidfantasy** [comment]
你的contextPath似乎有点问题，我看启动日志上显示的是“/common”。默认的应该是空，所以直接访问http://localhost:8068就可以了，你可以直接访问http://localhost:8068/common试一下，但是启动类并没有提供了contextPath的修改入口，你是直接修改了源码启动的？ 另外oracle数据库的schema一般等于其用户名
