### ISSUE TITLE
版本1.2.0：controller没有按设置生成方法

### ISSUE THREAD

**Issue by CsyDesign** [davidfantasy/mybatis-plus-generator-ui#22]
![image](https://user-images.githubusercontent.com/50761900/88456901-7cb6a080-ceb4-11ea-9d21-18a0e7c26ec0.png)
![image](https://user-images.githubusercontent.com/50761900/88456919-b5567a00-ceb4-11ea-89b2-53aa520db00b.png)

**Comment by davidfantasy** [comment]
我没有重现该问题，如果之前使用过老版本，可以尝试一下删除user.home下的.mybatis-plus-generator-ui文件夹，再清除一下浏览器缓存试一试

**Comment by wzc789376152** [comment]
确实没生成，我把1.2.1带的模板文件，在页面上传之后，就可以。默认情况不生成。

**Comment by davidfantasy** [comment]
可能是classload在加载模板时的优先级问题，现在的模板路径和mybatis-plus-generator中的模板路径是一致的，可能在你们的环境里面优先加载了mybatis-plus-generator中的模板，导致系统内置的模板失效了。我修改一下内置模板的路径再试一下吧

**Comment by davidfantasy** [comment]
1.2.2版已处理该问题
