### ISSUE TITLE
Sql代码生成Dto只有package信息bug

### ISSUE THREAD

**Issue by lpvus** [davidfantasy/mybatis-plus-generator-ui#23]
### 当前使用版本(必填,否则不予处理)
1.2.0
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
sql代码生成Dto，sql语句如果写带字段的如：
select `flow_id`, `ext_info` from `flow` where `call_sn` = 1
那么生成的dto 文件有错误

**Comment by davidfantasy** [comment]
1.2.1版本已修复该问题
