### ISSUE TITLE
如何设置生成实体类的字段名称不转成驼峰，而是使用数据库下划线的形式

### ISSUE THREAD

**Issue by IT-likanglin** [davidfantasy/mybatis-plus-generator-ui#27]
您好，我想设置生成的实体类的字段沿用数据库下划线的形式，请问怎么设置？
![clipboard](https://user-images.githubusercontent.com/42953162/91940215-aff91480-ed29-11ea-9366-9de939422f28.png)

**Comment by davidfantasy** [comment]
不需要修改源码，配置类中指定一个自定义的NameConverter，重新按你的需求实现 NameConverter的propertyNameConvert方法

**Comment by IT-likanglin** [comment]
谢谢大佬，已解决！
