### ISSUE TITLE
自动省略了表明第一个下划线之前的单词

### ISSUE THREAD

**Issue by icefery** [davidfantasy/mybatis-plus-generator-ui#28]
### 当前使用版本(必填,否则不予处理)
`1.3.2`
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
- 表名为`attribute_param`和`specification_param`生成的类名为`Param`，被自动覆盖了。
- 中间表`category_brand`生成为了`brand`
- 控制台日志信息如上描述
### 重现步骤(如果有就写完整)
1. 导入依赖`1.3.2`
2. main：
```java
public static void main(String[] args) {
    GeneratorConfig config = GeneratorConfig
        .builder()
        .jdbcUrl("jdbc:mysql://127.0.0.1:3306/demo")
        .userName("root")
        .password("root")
        .driverClassName("com.mysql.cj.jdbc.Driver")
        .basePackage("generator")
        .dateType(DateType.TIME_PACK)
        .port(8068)
        .build();
    MybatisPlusToolsApplication.run(config);
}
````
3. `entity`策略选择为：builder模式、lombox模式、`rest`模式、`mapping-url`模式

### 报错信息
无，运行正常

**Comment by icefery** [comment]
望作者大佬早带你修复哈

**Comment by icefery** [comment]
望作者大佬快快修复鸭

**Comment by davidfantasy** [comment]
这个不是问题哈，一般默认数据表的命名习惯都是t_xxx，所以默认把第一个下划线前的单词当成前缀去掉了。你如果不想这样，自定义NameConverter中的entityNameConvert方法就可以了

**Comment by icefery** [comment]
> 这个不是问题哈，一般默认数据表的命名习惯都是t_xxx，所以默认把第一个下划线前的单词当成前缀去掉了。你如果不想这样，自定义NameConverter中的entityNameConvert方法就可以了

昂好的知道啦，谢谢作者大佬哈

**Comment by icefery** [comment]
> 这个不是问题哈，一般默认数据表的命名习惯都是t_xxx，所以默认把第一个下划线前的单词当成前缀去掉了。你如果不想这样，自定义NameConverter中的entityNameConvert方法就可以了

作者作者，提个建议哈，看了一下下`NameConverter`接口，我觉得可以添加一些常用的模板方法，就不用自己写转换器了哈

**Comment by davidfantasy** [comment]
NameConverter中所有的接口方法都提供了默认实现，按照通常的项目约定的话一般不用自行再开发了，如果项目上有特殊情况才需要自行去实现接口

**Comment by icefery** [comment]
> NameConverter中所有的接口方法都提供了默认实现，按照通常的项目约定的话一般不用自行再开发了，如果项目上有特殊情况才需要自行去实现接口

好的嘛，-^^-
