### ISSUE TITLE
访问主页显示404

### ISSUE THREAD

**Issue by JerryTurtle** [davidfantasy/mybatis-plus-generator-ui#3]
1. 启动server后，访问localhost显示404，页面均不可使用，但是接口可以访问
2. 版本为1.0.4版本，回退到1.0.3版本之后恢复正常

**Comment by davidfantasy** [comment]
1.0.4版本更换了静态资源的映射目录，避免和本地的静态资源冲突。你可以尝试清除一下浏览器的缓存，再试一下，我本地测试是没有问题的

**Comment by xyhuangjia** [comment]
> 1.0.4版本更换了静态资源的映射目录，避免和本地的静态资源冲突。你可以尝试清除一下浏览器的缓存，再试一下，我本地测试是没有问题的

我这边也是不行的，降版本之后就可以了，但是会遇到生成第一层文件夹乱码

**Comment by xyhuangjia** [comment]
@davidfantasy 鶸运行 yarn run build 报错？然后鶸修改build.js 文件，碍于水平有限，没办法本地调试，不知道是不是1.0.4，localhost:8068 找不到原因
