### ISSUE TITLE
多模块项目如何将代码生成到对应模块中

### ISSUE THREAD

**Issue by xylearn921** [davidfantasy/mybatis-plus-generator-ui#32]
代码生成到添加mybatis-plus-generator-ui依赖的模块中，可以支持一下多模块项目吗，比如generator-ui单独放入一个模块中，通过配置将代码生成到其他模块中

**Comment by xylearn921** [comment]
![1605844428746](https://user-images.githubusercontent.com/23116938/99756012-17ec1980-2b27-11eb-88c7-6532d2460212.jpg)

**Comment by davidfantasy** [comment]
暂不支持将代码生成到项目之外的位置。建议可以在每个需要生成代码的模块都去集成mybatis-plus-generator-ui，只需要在test目录增加一个启动类即可，也不会影响到运行时的代码。

**Comment by hepking** [comment]
不好用，可定制性太差

**Comment by davidfantasy** [comment]
1.4.0版本可以独立部署并动态指定目标项目目录，可以满足你这个需求
