### ISSUE TITLE
目标项目根目录有问题

### ISSUE THREAD

**Issue by hdtopku** [davidfantasy/mybatis-plus-generator-ui#35]
### 当前使用版本(必填,否则不予处理)
1.4.0
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
![image](https://user-images.githubusercontent.com/14859466/105217481-df9ca200-5b8e-11eb-9c1d-7a64f046f948.png)

### 重现步骤(如果有就写完整)
模板项目根目录`Users/lxh/Desktop/mall/mall-mbgp/`应该为`/Users/lxh/Desktop/mall/mall-mbgp/`，上面的目录加上`/`以后，就可以生成了，不过下面的情况没法加上`/`
### 报错信息
在生成和sql代码生成时都会报错：
```
XML文件不存在：Users/lxh/Desktop/mall/mall-mbgp/src/main/resources/dao.xml
```
![image](https://user-images.githubusercontent.com/14859466/105217872-63ef2500-5b8f-11eb-937b-aef4f56bd84b.png)

**Comment by davidfantasy** [comment]
你用的是linux系统？下个版本会调整一下

**Comment by hdtopku** [comment]
好的

**Comment by hdtopku** [comment]
好的

**Comment by hdtopku** [comment]
```
      <dependency>
          <groupId>com.github.davidfantasy</groupId>
          <artifactId>mybatis-plus-generator-ui</artifactId>
          <version>1.4.1</version>
          <scope>compile</scope>
      </dependency>
```
依赖找不到，是不是还没更新

**Comment by davidfantasy** [comment]
刚发布，要等几个小时才能在maven库搜到

**Comment by hdtopku** [comment]
已测试，没问题了！
