### ISSUE TITLE
请问generator代码时，如何自动为createtime和updatetime生成@TableField注解

### ISSUE THREAD

**Issue by hdtopku** [davidfantasy/mybatis-plus-generator-ui#36]
#### 当前使用版本(必填,否则不予处理)
1.4.0

#### 问题详情
想使用createtime和updatetime字段自动填充功能，可是generator模板配置没找到方法
```
@TableField(value = "create_time", fill = FieldFill.INSERT)
```
#### 复现步骤
在creatime和updatetime手动填充@TableField注解，很不方便，而且后期可能被覆盖。
#### 期望结果
如何在自动生成代码的时候，creatime和updatetime自动填充@TableField注解，达到createtime和updatetime自动更新的目的

#### 可能可行的方案
```
// 自动填充配置 
TableFill createTime = new TableFill("create_time", FieldFill.INSERT); 
TableFill updateTime = new TableFill("update_time", FieldFill.INSERT_UPDATE);
ArrayList<TableFill> tableFills = new ArrayList<>(); 
tableFills.add(createTime);
tableFills.add(updateTime); 
strategy.setTableFillList(tableFills);
```

**Comment by davidfantasy** [comment]
在1.4.1版本中，entity策略设置中已经添加了自动填充字段的设置，目前只能所有类统一进行设置，暂不支持对不同的entity定制不同的字段

**Comment by hdtopku** [comment]
已测试，自动填充字段可用！
