### ISSUE TITLE
带下划线命名的数据库表生成的entity名称不对

### ISSUE THREAD

**Issue by zjh599245299** [davidfantasy/mybatis-plus-generator-ui#38]
### 当前使用版本(必填,否则不予处理)
1.4.2

例如有个表为role_permission 生成出来的entity类是Permission 和permission表生成的Permission冲突了

**Comment by zjh599245299** [comment]
找到办法了 修改entityNameConvert即可

**Comment by ukhack** [comment]
.nameConverter(new NameConverter() {
// 加这个
                    @Override
                    public String entityNameConvert(String tableName){
                        if (Strings.isNullOrEmpty(tableName)) {
                            return "";
                        } else {
                            String[] s = tableName.split("_");
                            String name = s[0];
                            for (int i = 1; i < s.length; i++) {
                                name+=StrUtil.upperFirst(StrUtil.toCamelCase(s[i].toLowerCase()));
                            }
                            return name;
                        }
                    }
//...后面的不变
