### ISSUE TITLE
配置的Entity超类中的字段和数据库字段不支持驼峰映射

### ISSUE THREAD

**Issue by 936223001** [davidfantasy/mybatis-plus-generator-ui#41]
### 当前使用版本(必填,否则不予处理)  
1.4.2
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
在Entity的策略配置里，配置了实体类的超类，超类中有createTime字段，对应数据库中的create_time,在”实体类的公共字段“配置了createTime后，生成的实体类还是生成了createTime字段，没有生效，必须把超类中的createTime改成create_time才生效。就是说配置的Entity超类中的字段和数据库字段不支持驼峰映射。
### 报错信息
无

**Comment by davidfantasy** [comment]
这个地方可能描述的不太清楚，配置公共字段的时候就应该配置为数据库字段的原始名称（mybatis-plus-generator框架的处理机制就是这样的，参考https://gitee.com/baomidou/mybatis-plus/issues/IPNN9），比如配置create_time，但你的超类里面的字段不用改名，叫createTime没有问题
