### ISSUE TITLE
集成到微服务时一定要排除掉spring-webmvc，否则网关无法启动

### ISSUE THREAD

**Issue by IsYongzheng** [davidfantasy/mybatis-plus-generator-ui#49]
### 当前使用版本(必填,否则不予处理)
1.4.5
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
直接引用
` <dependency>
            <groupId>com.github.davidfantasy</groupId>
            <artifactId>mybatis-plus-generator-ui</artifactId>
            <version>${generator.version}</version>
            <scope>compile</scope>
        </dependency>`
### 报错信息
Parameter 0 of method modifyRequestBodyGatewayFilterFactory in org.springframework.cloud.gateway.config.GatewayAutoConfiguration required a bean of type 'org.springframework.http.codec.ServerCodecConfigurer' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'org.springframework.http.codec.ServerCodecConfigurer' in your configuration.
###解决方案
`        <dependency>
            <groupId>com.github.davidfantasy</groupId>
            <artifactId>mybatis-plus-generator-ui</artifactId>
            <version>${generator.version}</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-webmvc</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`

**Comment by davidfantasy** [comment]
代码生成器都是建议scope写test的，这块不需要打包到正式环境中
