### ISSUE TITLE
1.45集成测试404 1.43可以

### ISSUE THREAD

**Issue by gaojunjun2016** [davidfantasy/mybatis-plus-generator-ui#51]
1.4.5
1.4.5 启动后打开是404，切换到 1.4.3 可以正常使用。想知道是为什么
重现步骤(如果有就写完整)
找不到 localhost 的网页

**Comment by hdtopku** [comment]
试试
```shell
npm i @babel/preset-env@7.12.17
```

**Comment by LiuRuiPeng2333** [comment]
![image](https://user-images.githubusercontent.com/44105320/212083394-64b79af3-c11b-4dc9-bd68-eb0e1dfc7c8b.png)
源码编译为啥还要python环境
