### ISSUE TITLE
启动失败，提示组件循环依赖

### ISSUE THREAD

**Issue by VWmin** [davidfantasy/mybatis-plus-generator-ui#53]
### 当前使用版本(必填,否则不予处理)
1.4.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
springboot 2.6.3 启动该项目时报错，提示组件循环依赖
降到之前用的2.4.3就正常过了

### 报错信息
![image](https://user-images.githubusercontent.com/34272476/154804757-234992c8-6add-4a55-a2a9-8a5f3627739d.png)

**Comment by wzc789376152** [comment]
我也遇到了这个问题

**Comment by davidfantasy** [comment]
这个是高版本springboot导致的问题，2.0.0已经解决了
