### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by strongyc** [davidfantasy/mybatis-plus-generator-ui#63]
### 当前使用版本(必填,否则不予处理)
2.0.0
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
springboot 2.7.9 ，数据库mysql 启动报错
### 重现步骤(如果有就写完整)
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mbpGeneratorController': Unsatisfied dependency expressed through field 'mbpGenerator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mbpGenerator' defined in URL [jar:file:/D:/maven/repository/com/github/davidfantasy/mybatis-plus-generator-ui/2.0.0/mybatis-plus-generator-ui-2.0.0.jar!/com/github/davidfantasy/mybatisplus/generatorui/mbp/MbpGenerator.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'beetlTemplateEngine' defined in class path resource [com/github/davidfantasy/mybatisplus/generatorui/ApplicationConfigure.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.github.davidfantasy.mybatisplus.generatorui.mbp.BeetlTemplateEngine] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]

**Comment by davidfantasy** [comment]
依赖包的版本冲突了，可以用相关工具检测一下（比如IDEA的dependency analyzer）看看具体是那个依赖，去掉冲突的依赖包就行了
