### ISSUE TITLE
启动后 访问页面报错

### ISSUE THREAD

**Issue by donglaidongwang** [davidfantasy/mybatis-plus-generator-ui#78]
### 当前使用版本(必填,否则不予处理)
2.0.1
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
 http://localhost:8098/api/db/tables 接口异常
{"code":500,"message":"系统发生内部错误，请联系管理员","data":null}
### 重现步骤(如果有就写完整)
1.参考官网进行配置启动
配置如下

        GeneratorConfig config = GeneratorConfig.builder()
                .jdbcUrl("jdbc:postgresql:172.20.X.X:55432/mydatabase")
                .userName("muuser")
                .password("pwd")
                .driverClassName("org.postgresql.Driver")
                // 数据库schema，POSTGRE_SQL,ORACLE,DB2类型的数据库需要指定
                 .schemaName("public")
                // 如果需要修改各类生成文件的默认命名规则，可自定义一个NameConverter实例，覆盖相应的名称转换方法：
                .nameConverter(new NameConverter() {
                    /**
                     * 自定义Service类文件的名称规则
                     */
                    @Override
                    public String serviceNameConvert(String tableName) {
                        return this.entityNameConvert(tableName) + "Service";
                    }

                    /**
                     * 自定义Controller类文件的名称规则
                     */
                    @Override
                    public String controllerNameConvert(String tableName) {
                        return this.entityNameConvert(tableName) + "Controller";
                    }
                }).basePackage("com.xx.service.domain.demo2").port(8098).build();

        MybatisPlusToolsApplication.run(config);
2.访问页面报错
### 报错信息
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

感觉给的配置没起作用，debug 发现  DataSourceConfig 配置里的 url    username
  password   也是给定的   但是实际查询的时候有问题

**Comment by davidfantasy** [comment]
数据库没连接上，检查数据库的连接配置
