### ISSUE TITLE
生成的entity中对于日期类型默认使用的是Date类型，如果想使用LocalDateTime的话如何处理？

### ISSUE THREAD

**Issue by Spring-Wave** [davidfantasy/mybatis-plus-generator-ui#79]
### 当前使用版本(必填,否则不予处理)
2.0.1

**Comment by davidfantasy** [comment]
GeneratorConfig里面有对日期类型的选型：
 
 /**
     * 数据库时间类型与java class的对应策略
     */
    private DateType dateType;
