### ISSUE TITLE
自动生成的时候，增加策略配置

### ISSUE THREAD

**Issue by Romic77** [davidfantasy/mybatis-plus-generator-ui#83]
### 当前使用版本(必填,否则不予处理)
2.0.1

### 增加策略配置
现在不够灵活。
MySQL的表名称为user_info，自动给我截了表前缀，生成了InfoMapper等等，期望有开关来控制表前缀问题

mybatisplus有策略配置更加灵活，可以控制表前缀的问题。

```

/**
     * 策略配置
     */
    private static StrategyConfig strategyConfig(String... include) {
        return new StrategyConfig.Builder()
                .addInclude(include) // 包含的表名
                .addTablePrefix("wt_") //统一表前缀
                .entityBuilder()  // 实体相关配置
                .naming(NamingStrategy.underline_to_camel)
                .columnNaming(NamingStrategy.underline_to_camel)
                .enableLombok()
                .build();
    }

```

**Comment by davidcharming8888** [comment]
加一段就行了
.nameConverter(new NameConverter() {
                    @Override
                    public String entityNameConvert(String tableName) {
                        return StrUtil.upperFirst(StrUtil.toCamelCase(tableName.toLowerCase()));
                    }
.xxx

**Comment by davidfantasy** [comment]
这个是默认数据表处理策略的问题，你可以自定义NameConverter中的entityNameConvert方法
