### ISSUE TITLE
jdbc driverClassName 写死了

### ISSUE THREAD

**Issue by jackxu2011** [davidfantasy/mybatis-plus-generator-ui#9]
### 当前使用版本(必填,否则不予处理)
1.0.4
### 该问题是如何引起的？(确定最新版也有问题再提!!!)
无法设置driverClassName("oracle.jdbc.OracleDriver")
### 报错信息
![image](https://user-images.githubusercontent.com/4495830/84742629-5400d880-afe3-11ea-95ed-28f907223743.png)

**Comment by davidfantasy** [comment]
已处理，将在下一个版本中修复该问题

**Comment by davidfantasy** [comment]
版本1.1.0已修复

**Comment by jackxu2011** [comment]
ok
